"""add incident simulation field

Revision ID: 05309b1bea50
Revises: 7b0872851250
Create Date: 2026-08-29 22:14:46.528668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '05309b1bea50'
down_revision = '7b0872851250'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('simulation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'simulation')
    # ### end Alembic commands ###