"""add workspace notification webhook url

Revision ID: 642d6b0c3902
Revises: 8c9c3da1b06a
Create Date: 2026-10-03 11:13:44.546562

"""
from alembic import op
import sqlalchemy as sa


revision = '642d6b0c3902'
down_revision = '8c9c3da1b06a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('notification_webhook_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'notification_webhook_url')
    # ### end Alembic commands ###