"""init

Revision ID: 7b0872851250
Revises: 
Create Date: 2026-08-29 22:10:29.765143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7b0872851250'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_deployed_at'), 'deployments', ['deployed_at'], unique=False)
    op.create_index(op.f('ix_deployments_service_name'), 'deployments', ['service_name'], unique=False)
    op.create_index(op.f('ix_deployments_workspace_id'), 'deployments', ['workspace_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('primary_service', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_workspace_id'), 'incidents', ['workspace_id'], unique=False)
    op.create_table('metric_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', 'recorded_at')
    )
    op.create_index(op.f('ix_metric_points_metric_name'), 'metric_points', ['metric_name'], unique=False)
    op.create_index(op.f('ix_metric_points_service_name'), 'metric_points', ['service_name'], unique=False)
    op.create_index(op.f('ix_metric_points_workspace_id'), 'metric_points', ['workspace_id'], unique=False)
    op.create_index('ix_metrics_workspace_service_metric_time', 'metric_points', ['workspace_id', 'service_name', 'metric_name', 'recorded_at'], unique=False)
    op.create_table('service_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('caller', sa.String(length=255), nullable=False),
    sa.Column('callee', sa.String(length=255), nullable=False),
    sa.Column('current_latency_ms_p50', sa.Float(), nullable=False),
    sa.Column('current_latency_ms_p99', sa.Float(), nullable=False),
    sa.Column('current_error_rate', sa.Float(), nullable=False),
    sa.Column('current_latency_variance', sa.Float(), nullable=False),
    sa.Column('reference_latency_ms', sa.Float(), nullable=False),
    sa.Column('reference_error_rate', sa.Float(), nullable=False),
    sa.Column('reference_latency_stddev', sa.Float(), nullable=False),
    sa.Column('reference_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('baseline_throughput_rps', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'caller', 'callee', name='uq_edge_workspace_pair')
    )
    op.create_index(op.f('ix_service_edges_workspace_id'), 'service_edges', ['workspace_id'], unique=False)
    op.create_table('service_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_service_workspace_name')
    )
    op.create_index(op.f('ix_service_nodes_workspace_id'), 'service_nodes', ['workspace_id'], unique=False)
    op.create_table('spans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('span_id', sa.String(length=32), nullable=False),
    sa.Column('parent_span_id', sa.String(length=32), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('span_name', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('status_code', sa.String(length=16), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', 'started_at')
    )
    op.create_index(op.f('ix_spans_service_name'), 'spans', ['service_name'], unique=False)
    op.create_index(op.f('ix_spans_trace_id'), 'spans', ['trace_id'], unique=False)
    op.create_index(op.f('ix_spans_workspace_id'), 'spans', ['workspace_id'], unique=False)
    op.create_index('ix_spans_workspace_service_started', 'spans', ['workspace_id', 'service_name', 'started_at'], unique=False)
    op.create_index('ix_spans_workspace_started', 'spans', ['workspace_id', 'started_at'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reasoning_endpoint_url', sa.String(length=512), nullable=True),
    sa.Column('reasoning_api_key_encrypted', sa.String(length=1024), nullable=True),
    sa.Column('reasoning_provider_label', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('incident_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reasoning_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('provider_tier', sa.String(length=32), nullable=False),
    sa.Column('hypothesis', sa.String(length=4096), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('proposed_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cited_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('simulation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reasoning_results')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('workspaces')
    op.drop_index('ix_spans_workspace_started', table_name='spans')
    op.drop_index('ix_spans_workspace_service_started', table_name='spans')
    op.drop_index(op.f('ix_spans_workspace_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_trace_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_service_name'), table_name='spans')
    op.drop_table('spans')
    op.drop_index(op.f('ix_service_nodes_workspace_id'), table_name='service_nodes')
    op.drop_table('service_nodes')
    op.drop_index(op.f('ix_service_edges_workspace_id'), table_name='service_edges')
    op.drop_table('service_edges')
    op.drop_index('ix_metrics_workspace_service_metric_time', table_name='metric_points')
    op.drop_index(op.f('ix_metric_points_workspace_id'), table_name='metric_points')
    op.drop_index(op.f('ix_metric_points_service_name'), table_name='metric_points')
    op.drop_index(op.f('ix_metric_points_metric_name'), table_name='metric_points')
    op.drop_table('metric_points')
    op.drop_index(op.f('ix_incidents_workspace_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_deployments_workspace_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_service_name'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_deployed_at'), table_name='deployments')
    op.drop_table('deployments')
    # ### end Alembic commands ###