"""add deployment config snapshot

Revision ID: 8c9c3da1b06a
Revises: be092de84e7c
Create Date: 2026-10-03 09:16:18.067588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '8c9c3da1b06a'
down_revision = 'be092de84e7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'config_snapshot')
    # ### end Alembic commands ###