"""add cohort dimensions

Revision ID: aa6e9b8c06f5
Revises: e84ae13194bc
Create Date: 2026-09-01 10:46:12.349504

"""
from alembic import op
import sqlalchemy as sa


revision = 'aa6e9b8c06f5'
down_revision = 'e84ae13194bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort_dimensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('attribute_key', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohort_dimensions_workspace_id'), 'cohort_dimensions', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cohort_dimensions_workspace_id'), table_name='cohort_dimensions')
    op.drop_table('cohort_dimensions')
    # ### end Alembic commands ###