"""add pipeline events

Revision ID: be092de84e7c
Revises: f80ded68cb09
Create Date: 2026-09-07 09:58:07.310911

"""
from alembic import op
import sqlalchemy as sa


revision = 'be092de84e7c'
down_revision = 'f80ded68cb09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_events_occurred_at'), 'pipeline_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_pipeline_events_workspace_id'), 'pipeline_events', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_events_workspace_id'), table_name='pipeline_events')
    op.drop_index(op.f('ix_pipeline_events_occurred_at'), table_name='pipeline_events')
    op.drop_table('pipeline_events')
    # ### end Alembic commands ###