"""add SLO definitions and SLI rollup table

Revision ID: c9299db20991
Revises: 642d6b0c3902
Create Date: 2026-10-03 14:18:28.732663

"""
from alembic import op
import sqlalchemy as sa


revision = 'c9299db20991'
down_revision = '642d6b0c3902'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_sli_rollups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('hour_bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'service_name', 'hour_bucket', name='uq_sli_rollup_workspace_service_hour')
    )
    op.create_index(op.f('ix_service_sli_rollups_workspace_id'), 'service_sli_rollups', ['workspace_id'], unique=False)
    op.create_table('slo_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('target_percent', sa.Float(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alert_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'service_name', name='uq_slo_workspace_service')
    )
    op.create_index(op.f('ix_slo_definitions_workspace_id'), 'slo_definitions', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slo_definitions_workspace_id'), table_name='slo_definitions')
    op.drop_table('slo_definitions')
    op.drop_index(op.f('ix_service_sli_rollups_workspace_id'), table_name='service_sli_rollups')
    op.drop_table('service_sli_rollups')
    # ### end Alembic commands ###