"""add service node risk baseline

Revision ID: f80ded68cb09
Revises: aa6e9b8c06f5
Create Date: 2026-09-02 23:40:54.049356

"""
from alembic import op
import sqlalchemy as sa


revision = 'f80ded68cb09'
down_revision = 'aa6e9b8c06f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added on all NOT NULL columns below (not in the
    # original autogenerated version) -- without it, Postgres has
    # nothing to backfill existing rows with when adding a NOT NULL
    # column to a table that already has data, and the migration fails
    # with a NotNullViolation. This only ever showed up against a real
    # database with existing service_nodes rows; every test of this
    # migration during development ran against a freshly created,
    # empty database, where the same bug is invisible because there
    # are no existing rows to violate the constraint. Matches the
    # model's own Python-level defaults (0.0 / 0).
    op.add_column('service_nodes', sa.Column('current_risk_score', sa.Float(), nullable=False, server_default='0'))
    op.add_column('service_nodes', sa.Column('risk_score_variance', sa.Float(), nullable=False, server_default='0'))
    op.add_column('service_nodes', sa.Column('risk_scan_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('service_nodes', sa.Column('reference_risk_score', sa.Float(), nullable=False, server_default='0'))
    op.add_column('service_nodes', sa.Column('reference_risk_stddev', sa.Float(), nullable=False, server_default='0'))
    op.add_column('service_nodes', sa.Column('reference_risk_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_nodes', 'reference_risk_updated_at')
    op.drop_column('service_nodes', 'reference_risk_stddev')
    op.drop_column('service_nodes', 'reference_risk_score')
    op.drop_column('service_nodes', 'risk_scan_count')
    op.drop_column('service_nodes', 'risk_score_variance')
    op.drop_column('service_nodes', 'current_risk_score')
    # ### end Alembic commands ###